ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

default_language_version:
  node: 16.15.0

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-symlinks
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort
    entry: isort
    require_serial: true
    language: python
    types:
    - python

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  -   id: absolufy-imports
